spring:
  application:
    name: ${APPLICATION_NAME:demo1}
  # Data Source properties
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/vlad?currentSchema=${spring.application.name}}
    username: ${DB_LOGIN:vlad}
    password: ${DB_PASSWORD:vlad}

  flyway:
    locations: db.migrations
    user: vlad
    password: vlad
    baseline-on-migrate: true

